### ISSUE TITLE
Basic Trees - Team 3

### ISSUE THREAD

**Issue by whiteya** [UQdeco2800/deco2800-2017-rocketpotatoes#10]
# Description

The game needs a larger variety of trees the player can build to expand on the strategy options.  There will be a base tree type and multiple variants and upgrades.

## Subfeature

- Ability to use projectiles and effects for trees (tree spawns projectile with initial inputs and the projectile acts according to how group 14 makes it)
- Basic tree with upgrades (Basic Tree I, Basic Tree II)
- Upgrades for trees
- Basic stats for trees
- Ability to build basic tower with right click (controls may be changed)

## Examples
A general tree has:
- Health
- Effect
- position (x,y)
- Damage / Effect Scale
- Build conditions (time, resources)
- bullet/effect trigger time (seconds between firing)
- stats need to be easily editble to allow other teams to rebalance

General Upgrades
- Changed stats (health, trigger time)
- Changed efffect/bullet
- Upgrade conditions (time, resources)

# Dependencies
#14 for shooting
#5 for construction conditions

# Milestone
- [x] Create general tree framework
- [x] Create a basic trees (Basic Tree I, Basic Tree II)
- [x] Allow player to build basic towers
- [x] Add upgrade mechanics
- [x] Add upgrades to the basic tree

# Extras
- [x] Varied graphics for construction in progress for trees (graphics, animations)
- [x] Further tree types using different projectiles from #14 
- [x] Add a way for different trees to be build (very extra, maybe part of something else)

# potential tree types
- Standard projectile
- - upgrades: speed, hp, damage, range 
- aoe projectile
- - upgrades: speed, hp, damage, range, area 
- triangular aoe projectile
- -  upgrades: speed, hp, damage, range, angle
# Members of Group 03
@whiteya
@Comquack 
@thegodfatherv 
@Bui1211
