### ISSUE TITLE
Player Character Attributes/Abilities - Team 4

### ISSUE THREAD

**Issue by aishadalila** [UQdeco2800/deco2800-2017-rocketpotatoes#12]
## Description

For this feature, we will focus on the player's primary abilities as well as its attributes. Because this is a tower (tree) defense game, the player will need to be equipped with certain attributes.

## SubFeature/component (optional)

Player's Abilities:
There are four main attributes of the players:

Attribute | Description | How it works? 
-- | -- | -- 
Strength | Determine the player’s endurance. It will focus on the player’s maximum health rate and health recovery rate from attack. The player will also have a strength stat that displays how much they could carry in their inventory. |  Each point of strength enables the player either to increase their health by 10% or increase their health recovery rate by 5% per minute.
Agility | Determines the player's dexterity and rate of movement. It will focus on the player's speed to build towers (trees). | Each point of agility enables the player either to increase their speed by 15%. 
Immunity | Determine the player's maximum restoration power. It will focus on the player to restore the towers (trees) as well as the regeneration of the potatoes plantation. | Each point of immunity enables the player to either restore the towers by 10% or potatoes plantation by 5%.
Power | Determine the player's special abilities. It will focus on the player's ability to increase their power in order to grow trees faster. | The player's special abilities will be upgraded based on the items/inventories found by the player throughout the game.

# **Dependencies**

Currently, there is no dependency of this ticket since it is the first implementation of the player's abilities. However, there is also other tickets that can be collaborated with this ticket which is ticket #5 and #19.

# **Milestone**

List of features you intend to have done and in Master by Checkpoint 1
- [ ] Player's strength attribute
- [ ] Player's agility attribute
- [ ] Player's immunity attribute
- [ ] Player's power attribute

# **Extras (Optional)**
- [ ] Upgrading the design of the player

# **Members of Group 4**
- Nik Aisha Dalila Binti Shamsul Anuar (@aishadalila)
- Tazman Stephen Schmidt(@TazmanSchmidt)
- Rachel Roesly (@rroesly)
- Joseph Sonny Seefeld (@sonnyseefeld)
