### ISSUE TITLE
Projectiles - Team 7

### ISSUE THREAD

**Issue by cronares** [UQdeco2800/deco2800-2017-rocketpotatoes#14]
# **Description**
Every tower in the game will be able to shoot projectiles to defend the base from the enemies, so, what our team will do is to create these projectiles with different damages, effects, statuses and animation that can stop the enemy from reaching the base. 

These projectiles will have the capabilities to fly and hit the enemies from a certain distance, as the level of the tower increases, the range of the projectiles will increase.

# **SubFeature/component**

- Different projectiles (Depends on which tower and which entity)
- Types of projectiles 
   * Homing
      * > Depends on what type of Towers #10  is going to develop eg. Fire tree tower, Wind tree tower?
Currently we are using rockets as our homing projectile.
   * Non-Homing (AOE)
      * > Depends on what type of Towers #10  is going to develop eg. Fire tree tower, Wind tree tower? 
Currently we are using rockets  as our non-homing projectile. Different types of rockets  can be used for different tower variations. 

![non-homing aoe projectiles](https://user-images.githubusercontent.com/3063877/29159796-2ca32cf4-7df3-11e7-8375-1c8c44d0ac37.png)
![homing projectiles](https://user-images.githubusercontent.com/3063877/29159797-2cd4339e-7df3-11e7-9a4a-ab8926bb7991.png)

# **Examples**

When the enemies come into the range of the tower, the tower will shoot projectiles at the enemies, giving it statuses such as slow and damage or probably just rips the enemies apart. The projectiles should have animation on impact and on launch.

A projectile will have various properties taken from #10 and attaching the values to the it.
- Amount of Damage that it's going to deal
- Statuses and effects
- Target (x,y)

# **Dependencies**

Projectiles relies on Towers for their range, attack damage, effects and statuses. It also relies on enemies for their current position (homing projectiles)
#10 for Towers (Trees) range, attack damage, effects and statuses
#15 for enemies coordinates to be used with homing projectiles

# **Milestone for checkpoint 1**
### **Checkpoint 1**
- [x]  Start / end, Impact/explosion 
- [x]  Projectile rotation
- [x]  Homing

### **Code Implementation**
- [x] Implement the homing projectiles to attack the exact enemy targets
- [x] Implement the Non-homing (AOE) projectiles to attack the assigned area of enemy, continually reducing enemies' health

### **Graphic**
- [x] Homing rockets with different fire frame to display a firing animation, such as fire at first, middle and the end of explosion
- [x]  Non-homing(AOE) explosion graphic as a basic circle for the AOE impact on the gaming map
- [x] The rocket start-firing and explosion sprites for homing projectiles
- [x] Non-homing projectile sprite (rockets) and firing animation

# **Extras**

- Magical capabilities instead of just rockets etc (eg. lightning)
- Laser
 
# **Members of Team 7**

Tingxi Lu (@Alexlou1390)
Tristan Cargill (@Monshi10x)
Wei Sheng Ding (@cronares)
Joseph Zhuang Chern Teo (@josephteo548)
