### ISSUE TITLE
Enemies/EnemyTypes - Team 11

### ISSUE THREAD

**Issue by ryanjphelan** [UQdeco2800/deco2800-2017-rocketpotatoes#15]
# **Description**

Main idea here is to create a base enemy type, something that any subsequent enemies will be based around. i.e. there is a "speedy" squirrel or a "tank" squirrel. Both of these sub-types will have a similar construction to the base enemy. Having this will enable enemy standardization and make the addition of extra enemy types easier.

# **Subfeatures**

Enemy Health
Attack preference
Attack Strength
Destination/Goal depending on type
Speed can be dependent on level
Choice to attack either player or towering depending on location/game mode.

# **Milestones**

- [x] Complete base AbstractEnemy class
- [x] Give enemies a base stats class to control their behaviour
- [x] Give enemies more structured goals (e.g. move toward GoalPotate (nexus) but attack tower's if nearby)
- [x] Create one or more enemy type - e.g. TankEnemy
- [x] Create more than one enemy type
- [x] Allow enemies to attack other entities

# **Members of Team 11**

 - Ryan Phelan (slack: “ryanjphelan”)
 - Craig Harvey (slack: “craig”)
 - Blair Garton (slack: “lambo-blair”)
 - Qishi Zheng (slack: “qishi”)
 - Wei Shan Liew(slack:"tl")
