### ISSUE TITLE
Multiplayer Backend with Chat System and Simple Connection System - Group 8

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#16]
# **Description**

A multiplayer backend with a simple chat system for system, game and player messages. The purpose of this backend is to allow an easy API for others to interface their systems and easily transfer data between clients. The internal system will have a client as a host, and all other clients connecting to that host. Said host will then be a single contact and broadcast point for other clients. This is intended to be fairly basic and will not have advanced features like host migration in the cases of dropping or bad hosts. 

## SubFeature/component (optional)

- **Chat Interface**: a simple demonstration of the chat system allows users to send messages to each other in a single game. Also allows various system and gameplay messages to be broadcast.
- **Connection Interface**: system interface overlay for connecting directly to an IP with a port (and eventually a user defined name)

# **Milestone**
- [x] Simple client and host with simple data transfer and chat messages
- [x] Basic protocols for entity creation/deletion/updating
- [x] Backend for connection interface (Direct IP connection)
- [x] Multiple clients with a single host
- [x] Broadcasting of simple chat messages to all clients (Client -> Host -> Other clients)
- [x] Development of chat interface (names, colors)

# **Extras (Optional)**
- [x] Details of network protocols, guidelines and advice on structuring future features so they can integrate well with multiplayer 

# **Members of group XX**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)
- Tze Lok Cheng (GH: @githubIC Slack: @ic)
- Dean Wyatt (GH: @Deanosity Slack: @deanosity)
- Rongjie Lin(GH: @rongjielin  Slack: @rongjielin)
- Jacob Jie Dong (GH: @TheLousyOne Slack: @thelousyone)

# **Relevant Documentation** 
- https://github.com/UQdeco2800/deco2800-2017-rocketpotatoes/wiki/AbstractEntities-(How-To---Guidelines)#multiplayer
- https://github.com/UQdeco2800/deco2800-2017-rocketpotatoes/wiki/Multiplayer
- https://github.com/UQdeco2800/deco2800-2017-rocketpotatoes/wiki/Multiplayer-Protocols
