### ISSUE TITLE
Resource Tree Team 5

### ISSUE THREAD

**Issue by anguscasey** [UQdeco2800/deco2800-2017-rocketpotatoes#17]
# Description:
We will be designing a resource tree for rocket potatoes. After being placed on the map it will generate resources that can be used for future functions. Resources generated by these trees can be harvested by the player. Doing so transfers the resources into the player's inventory for safe keeping.

# Features
Design:
- [x] Base Seed Resource Tree Sprite
- [x] Alternate Resource Tree Sprite

Sound:
- [x] Harvest Sound Effect

Mechanics:
- [x] Resource Tree can be spawned
- [x] Resource Tree has upgrade stats
- [x] Resource Tree can add or remove resources by amout
- [x] Resource Tree can gather resources over time
- [x] Resource Tree has type based on resource it gathers
- [x] Resource Tree has a resource gather limit
- [x] Resource Tree can transfer resources to an inventory (harvest)

Bonus:
- [x] Display the gather count of a resource tree on screen
- [x] Plant trees with keyboard numbers

**Dependencies**:
- Ticket #5: Using resources and inventory
- Ticket #10: Using basic tree and timed event

# Design
- 3D based isometric design influences by crossy roads.
- Bold colours with no 'black lines' around image borders.
- 3 construction sprites that will start as a sprout and 'grow' (change sprite) as the tree grows.

# Current Resource Tree Designs

The tree will be split into three construction sprites that will change as the tree grows. The alpha design are below:

- Resource Sprout
![sprout github ticket 5](https://user-images.githubusercontent.com/12975396/29748914-08555722-8b64-11e7-91fa-8dba47adae94.PNG)

- Resource Half Tree
![half tree github ticket 5](https://user-images.githubusercontent.com/12975396/29748913-0672c1a6-8b64-11e7-9689-1cd264fddec7.PNG)

- Seed Resource Tree
![basicresourcetree-01](https://user-images.githubusercontent.com/30395421/29713087-605e20c8-89e0-11e7-88e6-46e9ba030b36.png)

- Future Design Ideas:
<img width="242" alt="capture" src="https://user-images.githubusercontent.com/30395421/29713577-92d103e8-89e2-11e7-8111-a28c1fded652.PNG">

# Future Development Ideas (Beyond CP1)

In further tickets (dependent on other groups) we plan to pick up seeds for construction of the first tree by killing squirrels:
1. Dead Squirrels would drop _x_ seeds

**Ideas for other resources produced by tree:**
1. Ammo for projectile trees
2. Health for Character
3. Health for surrounding trees

**Milestones:**
Have design, sounds and mechanics created by checkpoint one.

Angus Casey (@anguscasey)
Peter Condoleon (@petercondoleon)
Joe Chay (@ailerone)
wei qing chin (@qing)
Nik Aisha Dalila Binti Shamsul Anuar (@aishadalila)
