### ISSUE TITLE
Skill/Tech Progression System - Team 5

### ISSUE THREAD

**Issue by petercondoleon** [UQdeco2800/deco2800-2017-rocketpotatoes#19]
# Description:
A system for keeping track of the progression of player and tower (tree) abilities. 
**Note:** This feature is not a means to implement player abilities and tower (tree) upgrades. It is designed for managing their progression through the course of a play-through. Read below.

### Attribute Points (AP) 

- Allows the player to buy certain attributes.
- Received every time the player levels up.

### Skill Points (SP)

- Allows player to increase the skill of an attribute.
- Earned by using the attribute.

### Examples of attribute and their skill levels

Attribute | Skill lvl 1 | Skill lvl 2 | Skill lvl 3
-- | -- | -- | --
Strength | 25% more player  damage dealt. | 50% more player damage dealt. | 75% more player damage dealt.
Dexterity | Move 30% faster. | Move 60% faster. | Move 100% faster.
Intelligence | Can build level 1 towers. | Can build level 2 towers. | Can build level 3 towers.
Repair | Can repair resource type towers. | Can repair offensive type towers. | Can repair defensive type towers.

## Tower (tree) tech progression:
Three types of trees: Resource, Offensive and Defensive.

### Resources
- Healing certain HP (Active)
- Increase production on Resource tree (Passive)
- Increase chances for magic compose drops (Passive)

### Defensive
- Temporarily Invincibility on all towers (Active)
- Temporarily invincible for player (Active)
- Temporarily Increase in Defence (Active)
- Temporarily increase walking speed (Active)

### Offensive
- Temporarily Increase in Attack Speed (Active)
- Fireball (Active)
- Permanent increase tower attack range 

# Dependencies:
Basic Trees #10 - Incorporating tree upgrades with tech progression
Health and Dying #2 - Incorporating modification on units damage intake and regeneration with tech progression
Projectile #7 - Incorporating modification on units damages, range, and statuses with tech progression

# Milestones:
To be implemented prior to checkpoint 1.
- [ ] Player progression manager
- [ ] Generic player attributes 
- [ ] Skill levels for attributes
- [ ] Tree progression manager
- [ ] Generic tree upgrade
- [ ] Tiers for upgrades

Angus Casey (@anguscasey)
Peter Condoleon (@petercondoleon)
Joe Chay (@Ailerone)
wei qing chin (@Qing)
