### ISSUE TITLE
Main Menu Interface + System - Team 8

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#22]
# **Description**

A main menu framework with some basic features implemented. This feature will include a way to start a singleplayer game or a multiplayer and will integrate with #16 with the connection interface (ip, name, port etc.). This main menu system will also include the implementation of some basic GUI elements which may include elements such as text boxes, sliders, drop down menus etc. This main menu will also include an option menu interface but will be fairly bare until we have more options to modify.

This ticket will also serve to refine the GUI backend and expand on the current GuiManager and Gui types, preferably in a dynamic way so components of a Gui can be reused.

If you have any specific ideas for things included in the option menu or any other suggestions please comment.

**State System Description:**
Main Menu -> Playing Game (SP or MP) <-> Pause Menu -> Main Menu
      |
     V
Option Menu

# **Milestone**
- [x] Simple Menu with a button that when pressed initializes the game (Separation of gameplay from the primary initialization of the application)
- [x] Way to enter singleplayer or multiplayer (Just hard-coded multiplayer initialization)
- [x] Multiplayer connection interface implemented from #16
    - [x] Text boxes
    - [x] Error boxes on failed connection
- [x] Option Menu
    - [x] Simple toggleable options (Check boxes)
    - [x] Music Volume slider
    - [x] Sound Effects Volume slider

# **Extras (Optional)**
- [x] A way to exit a playing game and go back to the main menu
- [x] Main Menu 'prettifying' with custom made art
- [x] Pause Menu

# **Members of group XX**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)
- Tze Lok Cheng (GH: @githubIC Slack: @ic)
- Dean Wyatt (GH: @Deanosity Slack: @deanosity)
- Rongjie Lin(GH: @rongjielin  Slack: @rongjielin)
- Jacob Jie Dong (GH: @TheLousyOne Slack: @thelousyone)

# **Relevant Documentation**
