### ISSUE TITLE
Tree Planting - Team 6

### ISSUE THREAD

**Issue by jholder96** [UQdeco2800/deco2800-2017-rocketpotatoes#23]
# **Description**
A way for players to spend resources on various entities. This will remove resources from the inventory and allow entities (such as trees) to be placed.

# **Dependencies**
#5 Inventory and resources
#17 Resource Tree
#10 Basic Tree

# **Milestone**

- [x] Design pop up menu for when ground is pressed
- [x] Create shop class to store tree costs and availability
- [x] Trigger pop up menu on press
- [x] Trigger plant tree action
# **Extras (Optional)**

# **Members of group XX**
- Jordan Holder (@jholder)
- Dion Lao (@dionode)
- Katherine Gray (@kgray)
- Kryssi Zhao (@ruoran)
- Julien Tran (@julien.t)
