### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#25]
# **Description**

Ability to efficiently create various types of particles. These should have a location, timeout, frequency, and other options that alter the appearance (like angles etc.) Right now the plan is to have simple colored particles, I don't think it's likely anyone would require larger more complicated particles and I doubt they would fit thematically.

Any suggestions are welcome!

# **Milestone**
- [x] Particle Creation (i.e. random directions) with fixed timeout
- [x] Options
    - [x] Emitters
        - [x] Multiple types
        - [x] Release n particles after t time
        - [x] Origin
        - [x] Timeouts
    - Particles
        - [x] Speed + speed variance
        - [x] Rotation
        - [x] Transparency settings, fadeout + ceilings
        - [x] Frequency
        - [x] Extras?
effects)

# **Members**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)

# Documentation
https://github.com/UQdeco2800/deco2800-2017-rocketpotatoes/wiki/particles
