### ISSUE TITLE
Terrain design - team 9 & 3

### ISSUE THREAD

**Issue by Sh4lidar** [UQdeco2800/deco2800-2017-rocketpotatoes#26]
# Description

Expanding on the map design by adding additional tile types and adding random map generation. Maps will generate based on a theme which consists of a set of tiles. Each theme will consist of some modified basic tile types.
Basic Tiles:
 - Varied height and incline (sloped, cliff)
 - Grass (Trees can be planted)
 - Rock (Trees can't be planted)
 - Water (Impassable)

Themes will include:
 - Normal
 - Snow
 - Others....

## Map Generator
The map generator will generate a map given a specific theme. 

# Milestone
## Team 9 - Graphics

Terrain types
Environment objects

- [x] grass
- [x] rock

Aesthetic enhancements
-------------------------
## Team 3 - Mechanics

- [x] Maps generated without tmx file
- [ ] Addition of Z coordinate
- [x] Basic tiles and map representation
- [x] Basic random map generator
- [x] implement impassable terrain
- [x] implement level changing
- [x] checking the player starting location is valid

## Team 3 - Extras

- [ ] Less variable terrain generation
- [ ] Valid point checking change to check terrain is accessible to player
- [ ] Different terrain generation for different world types
