### ISSUE TITLE
Portals - Team 6

### ISSUE THREAD

**Issue by dioNode** [UQdeco2800/deco2800-2017-rocketpotatoes#27]
# **Description**
Players can move between portals to move to different worlds with different terrains.

# **Dependencies**
#24 Map designs and constraints
#26 Terrain design

# **Milestone**
List of features you intend to have done and in Master by Checkpoint 2
- [x] Create portal class
- [x] Portal class tests
- [x] Instantiate portals in map
- [x] Collision event with portal that teleports player to new map

# **Members of group XX**
- Jordan Holder (@jholder)
- Dion Lao (@dionode)
- Katherine Gray (@kgray)
- Kryssi Zhao (@ruoran)
- Julien Tran (@julien.t)
