### ISSUE TITLE
Enemy Interactions and Types (Team 11)

### ISSUE THREAD

**Issue by charvei** [UQdeco2800/deco2800-2017-rocketpotatoes#29]
# **Description**
With the basic outline of enemies and the concept of the game becoming more defined, this issue is concerned with refining existing enemies and creating new enemies to represent a cunning force that meaningfully interacts with the battlescape. We aim to do this by improving existing and creating new enemy types that thematically interact with the player's world and defences to create interesting challenges for the player. With this we hope our enemies can inspire the player to meaningfully consider their strategies, e.g., tower choices, tower placements, resource collection & usage, and justify the tools at their disposal.

# **Sub-features**

**Refining existing enemies (Tank, Speedy & Squirrel):**

- Updating existing enemies to use the Enemy Movement API

- Setting goal to enemy base

- Improving of existing interactions such as attacking

- Refining enemy designs

- Potentially include enemy levels into base enemy class for later "levels" in the game

**Interesting Interactions**

- Creating new enemy interactions with the world (incl. map/terrain, player character, resources, tree types) with the purpose of promoting interest gameplay.

**Creating new enemies**

- Creating new enemies with features and interactions that are meaningful with game elements (e.g. a deer enemy that traverse obstacles or terrain that would be difficult for squirrels)

# **Milestones**

- [x] Rework melee attacking
- [x] Racoon stealing resources interaction
- [x] Bear (TankEnemy) special ability
- [ ] Squirrel and Bear character design
- [x] New enemies (Moose) with interesting interactions (random movement, attack player if close)
     - [x] attacks and follows player if nearby 
     - [x] heal enemies
     - [ ] Attack animation/type of attack (maybe charging)
- [x] Unit testing of generic enemy classes
- [x] Fix code smells (if any)
- [x] Bear (TankEnemy) "stomps" terrain. This broken terrain will slow down entities.
- [x] Enemies come as wavies
 
# **Members of Team 11**

 - Ryan Phelan (slack: “ryanjphelan”)
 - Craig Harvey (slack: “craig”)
 - Blair Garton (slack: “lambo-blair”)
 - Qishi Zheng (slack: “qishi”)
 - Wei Shan Liew(slack:"tl")
