### ISSUE TITLE
Enemies - Team 6

### ISSUE THREAD

**Issue by Leggy** [UQdeco2800/deco2800-2017-rocketpotatoes#3]
# **Description**
Enemies should be able to spawn from trees, move towards and attack targets (either towers or players) without colliding with anything, they should have stats for:
- target it's aiming for
- movement speed
- type of attack
- attack power
- attack speed
- range attack 
- health (max and current)
- resources to drop
And a way to display some/all of these values

Enemies will spawn and track players and, when they are in range, attack the players. A player can attack enemies and, if the player kills the enemy - by depleting its health, the killed enemy will disappear and be replaced by a resource. Enemies are vital to gameplay as they add difficulty. 

# **Dependencies**
tree graphic
resource graphic 
health bar
attack animations

# **Milestone**
- [ ] Two types of spawning enemies
- [ ] Tracking functionality
- [ ] Attack functionality
- [ ] Health bar and stats
- [ ] Resource dropping
# **Extras (Optional)**
- [ ] Addional enemies created from the same shell with stronger stats etc.

# **Members of group XX**
- Dion Lao (@dioNode)
- Jordan Holder (@jholder)
- Julien Tran (@julien.t)
- Katherine Gray (@katieg)
- Kryssi Zhao (@ruoran)
