### ISSUE TITLE
Collision Overhaul

### ISSUE THREAD

**Issue by ashfordneil** [UQdeco2800/deco2800-2017-rocketpotatoes#30]
# Description

Our collision system currently doesn't really fit our game. We use a 3D box class in a game where (1) most things are 2D and (2) most things don't have rectangular collision masks. Our goal is to make collision checking more abstract (to allow for different types of collision masks) and also 2D.

## Note on 2D

We are still in discussion with team 3 as to how the 3D components of the game are going to interact with the primarily 2D components of the game. There will be some modifications to this ticket in the near future.

# Dependencies

#10 interacts with this (see Note on 2D), though a separate ticket may be made specifically for that.

# Milestone

- [x] Creating a "CollisionMask" interface
- [x]  and integrating it into the game without any loss of functionality
- [x] Adding support for different shapes of collision mask

# Extras
- [ ] Physics around collisions (to be discussed in a prac)

# Members of Group 1 (that are working on this)

- Tazman Schmidt, @tazman_schmidt on slack
- Neil Ashford, @artemis on slack
