### ISSUE TITLE
Improved Inventory - Team 6 

### ISSUE THREAD

**Issue by katherinegray97** [UQdeco2800/deco2800-2017-rocketpotatoes#33]
# **Description**
The current inventory needs to be updated to comply with the newest direction of the overall game. Now that players can collect multiple items from multiple worlds, the inventory needs to be able to display all of these items in a user-friendly manner. The inventory GUI should take up minimal space, therefore it will probably be implemented as a scrolling list of items, with each item being displayed by its name and a small image. 

# **Dependencies**
- All of the resources to be displayed have to actually exist and have an associated texture.
  

# **Milestone**
List of features you intend to have done and in Master by Checkpoint 2
- [x] Displaying a GUI of many placeholder resources  
- [x] Displaying a scrollable GUI of placeholder resources 
- [x] Displaying a scrollable GUI of implemented resources 
- [x] Live updates for player's inventory

# **Members of group XX**
- Jordan Holder (@jholder)
- Dion Lao (@dionode)
- Katherine Gray (@kgray)
- Kryssi Zhao (@ruoran)
- Julien Tran (@julien.t)
