### ISSUE TITLE
Enemy waves and spawning (team 11)

### ISSUE THREAD

**Issue by charvei** [UQdeco2800/deco2800-2017-rocketpotatoes#40]
# Description
Creating and managing waves of enemies spawning and the wait periods in between. The flow of tower defense games are determined by the characteristics of enemy waves. Currently the plan is to have a set preparation period before each wave where the player can set up their base briefly, followed the start of a wave where enemies will spawn for a period of time. Also need to specify where enemies spawn from.

# Structure
## EnemyWave
A class that defines the composition of a wave (in form of ratios) and the length of time the wave will be. Special events within a wave e.g. a particular enemy spawning or some kind of world effect (if implemented) could likely be held here too.

## WaveManager
A manager class to manage enemy waves - when to start, end, pause and progress waves.

 ## WaveGUI
A small GUI for displaying: 
- Current wave position in list of all waves (game progression)
- Elapsed time/time to wave ends for currently active wave
- When next wave starts if in a preparation period

# Milestones
- [x] Enemy spawn location
- [x] Enemy staggered spawning over period of time
- [x] Allow for chains of multiple waves
- [x] GUI
- [x] Pausing waves
- [x] Wave difficulties increasing throughout game
    - [x] Waves generated as game runs
