### ISSUE TITLE
Expand and fix Multiplayer!

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#42]
# **Description**

 Multiplayer is *super* broken. Now that the game's underlying architecture is mostly dictated, i.e. how do we deal with enemies, building, world switching, exiting etc. Multiplayer can be _fixed_ to accommodate for these changes. It's likely this will become very broken again soon enough, but the intention is to make the multiplayer architecture a little more resilient to issues, and to minimize it's interference with game logic.

# **Milestone**
-  [ ] Entity syncing (creation, deletion, updating, timed events)
-  [ ] World syncing (Simulation of multiple worlds simultaneously)
-  [ ] Clean up of existing architecture
-  [ ] Improve 'resilience' (i.e. make mp not entirely break when someone doesn't mark something transient)
-  [ ] Player type selection for multiplayer
-  [ ] More?

# **Members**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)
