### ISSUE TITLE
Tutorial - Team 6

### ISSUE THREAD

**Issue by katherinegray97** [UQdeco2800/deco2800-2017-rocketpotatoes#47]
# **Description**
A walk-through tutorial first-time players can use to learn how to play our game. It will consist of pop-up GUI elements that explain certain features and how the player can interact with them. The player should be able to quit (and possibly revisit) the tutorial at any stage.  

# **Dependencies**
- At least part functionality of all major features in the game 
  
# **Milestone**
List of features you intend to have done and in Master by Checkpoint 3
- [x] Generic tutorial GUI element design
- [x] Implementation of a generic tutorial GUI element
- [x] Written tutorial script for each main feature in the game including how-tos for: 
    - [x] Player movement/controls
    - [x] The base portal
    - [x] Enemies 
    - [x] Resources 
    - [x] Trees
    - [x] Worlds
- [x] Implemented GUI elements for each of the above features
    - [x] Player movement/controls
    - [x] The base portal
    - [x] Enemies 
    - [x] Resources 
    - [x] Trees
    - [x] Worlds
- [x] Fully connected walk-through functionality at the start of the game, including the ability to exit the tutorial at any point

# **Members of group 6**
- Jordan Holder (@jholder)
- Dion Lao (@dionode)
- Katherine Gray (@kgray)
- Kryssi Zhao (@ruoran)
- Julien Tran (@julien.t)
