### ISSUE TITLE
CP3: More projectiles and weapon effects! -Team 7

### ISSUE THREAD

**Issue by josephteo548** [UQdeco2800/deco2800-2017-rocketpotatoes#53]
# **Description**
In CP3, our team 7 will keep working on improving the adding and  implementation of projectiles which include lighting attack debugging and player's direction shooting improvements. New projectiles for various trees for each world and player weapon projectiles will also be added. Ensuring that all projectile sprites scale properly in game. 

# **Projectiles** 
- Lasers- Solar beam
- Ice attack 
- Fire attack
- Leaf attack
- Mine planting animation

# **Player weapon**
- Charging energy orb
- Axe
- Arrow

# **Code work**
- Projectiles Collisions; Change projectiles collisions to Oval shape
- Charging projectile plasma orb
- Fix spawn location for projectiles (exact point like lightning)
- Rocket collision box => circle at tip
- Mine bombs with AOD effect (timer countdown)
- Fix player projectiles directional not working as intended
- Lightning strike point damage (check)
- Player Fire with mouse

# **Milestone**
Main goals and features that we need to complete in CP3
- [x] Scale all projectile sprites to fit game
- [x] Lasers - Solar beam animation design
- [x] Ice attack 
- [x] Fire attack 
- [x] Leaf attack
- [x] Acorn attack and throw code implementation
- [x] Mine planting implementation
- [x] New oval collisions for all projectiles
- [x] Player weapons
