### ISSUE TITLE
F̠̠̪̯ͤ̄ͅĭ͓̽ͯ̽ͅs̥̆̓ḧ̤̠̉͌́ͤͮi͔̼̱̼ͭ̈̿ͧn̟̙̖͍͖͕gͫ́ͣ̏ ̭̗͚̣͉͕͋̓̐̓̽̊ͯM̿̌͆ͩͬ͑ọ͙̰̳̭̙͌d̪̤̤̑̑̃͐ͪ̄̃e̊͊

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#64]
# **Description**
A meme mode for a separate Fishing game. Accessible by a yet to be determined cheat code. Ideally written in _Rust_.
Requires working with Team 1 with their cheat system.

# **Milestone**
- [x] Run a rust application as a library within the game
~~- [ ] Pass the opengl context to rust and draw (maybe not practical)~~
~~- [ ] Create a headless opengl context on the side of rust and pass back frames to be drawn~~
- [x] Setup callbacks for Java to render with
- [x] Callbacks for input processing (Likely to just be one key)
- [x] Interface with current cheat system
- [x] Make the fishing game
- [x] Ensure that it's not going to break Jenkins
- [x] Ensure it's not going to break on people's machines locally

# **Members**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)
- Neil Ashford (GH: @ashfordneil Slack: @artemis)
