### ISSUE TITLE
Improved Tree Planting - Team 6

### ISSUE THREAD

**Issue by katherinegray97** [UQdeco2800/deco2800-2017-rocketpotatoes#65]
# **Description**
Polishing off the tree planting menu implemented for CP2. This menu is technically functional currently but it needs more work to further integrate it into the game/improve its usability. This includes work on a "tree inventory" which tracks all the trees the player has learnt how to plant. See Milestones below for a more thorough description of these features. 

# **Dependancies**
- Completed sprites for all of the trees

# **Milestones**
List of features you intend to have done and in Master by Checkpoint 3
- [x] Hotkeys for the menu
- [x] Colour-coded resource/attack/defense trees to improve UI  
- [x] Softcoded tree costs displayed nicely 
- [x] Tree inventory tracking the trees the player has learnt
- [x] Ability to plant trees from multiple worlds

# **Branch we're working on**
Inventory

# **Members of Group 6**
- Jordan Holder (@jholder)
- Dion Lao (@dionode)
- Katherine Gray (@kgray)
- Kryssi Zhao (@ruoran)
- Julien Tran (@julien.t)
