### ISSUE TITLE
Player Sprint

### ISSUE THREAD

**Issue by petercondoleon** [UQdeco2800/deco2800-2017-rocketpotatoes#69]
# Description
Add the ability to make the player sprint by double tapping a movement key. Allows the player to traverse a larger world faster. 

# Tasks
The feature involves the following:

- [x] Double tapping a WASD key initiates sprint (by doubling the default speed).
- [x] Sync animations and sound effects with player move speed to match walk and sprint.
- [ ] Colliding with an entity or edge cancels the sprint.
- [ ] Bonus: colliding while sprinting makes a subtle screen shake effect.

# Contributors 
Feel free to add yourself to this list if you would like to help implement this feature.

- Peter Condoleon (@petercondoleon)
- Joseph Lay (@fff134)
