### ISSUE TITLE
Revamped Resource Trees

### ISSUE THREAD

**Issue by petercondoleon** [UQdeco2800/deco2800-2017-rocketpotatoes#71]
# Description
Clean up the resource trees by further improving on peer feedback as well as implement new features such as tree build animations and resource growing/harvesting animations.

# Tasks
The feature involves the following:

## New and improved resource trees
- [x] Green coloured seed resource tree 
- [x] Pink coloured food resource tree 
- [x] Brown coloured acorn resource tree 

## New textures and animations
- [x] Resource tree grow animation
- [x] Resource tree produce resource animation
- [x] Resource tree harvested from animation

## Attributes
- [x] Resource trees have states that determine their conditions and animations.

## Dependencies 
Ticket #73 - Overhaul of trees

# Contributors
Feel free to add yourself to this list if you would like to help implement this feature.

- Peter Condoleon (@petercondoleon)
- Aisha Dalila (@aishadalila)

# Members of Team 5
- Peter Condoleon (@petercondoleon)
- Aisha Dalila (@aishadalila)
- Angus Casey (@anguscasey)
- Joe Chay (@ailerone)
- Wei Qing Chin (@qing)
