### ISSUE TITLE
Overhaul of trees 

### ISSUE THREAD

**Issue by katherinegray97** [UQdeco2800/deco2800-2017-rocketpotatoes#73]
# **Description**
The plan for and purpose of trees has been rethought. We need to evaluate all current work, re-designing as much as possible and deleting everything else. We aim to make all trees in the game consistent in such a way that each tree has a distinct, logical purpose. 

We want: 
**Three resource trees** native to the forest world- each resource tree will be the same design, just a different colour (green, pink, brown). Its colour represents the _one_ resource it generates. Green resource trees create seeds, pink resource trees create food, brown resource trees create pinecones. These resources are the base cost for all other trees in the game. 

**One defence tree** native to the forest world- this will be cheap to plant but have a short lifespan. Player's can plant it when they are under pressure from enemies. Effectively, defence trees can be used as a road block or a distraction. They will only cost resources native to the forest world. 

**Five attack trees** 
- Acorn tree (native to forest world)
- Cactus tree (native to desert world) 
- Volcano tree (native to the volcano world)
- Lightning tree (native to ice world) 
- Coral tree (native to underwater world) 
Each attack tree will "fire" a coloured squiggly line to represent its attack. It will cause damage to enemies in range. Their cost of attack trees will comprise of the base resource items from the forest world and resource items native to their native worlds. For example, the lightning tree may cost 1 seed, 2 food, 3 pinecones, 1 seal skin, 1 ice crystal and 2 snowballs.
 
Note: we will also implement functionality involving resources spawning in other worlds after each enemy wave. This eliminates the need to introduce multiple resource trees for all of the resources and gives the player a reason to revisit worlds.

# **Milestones**
List of features you intend to have done and in Master by Checkpoint 3
Design and implementation of 
- [x] Resources spawning in other worlds after every wave
- [x] All attack trees designed and implemented, with projectile attack functionality
- [x] All three resources trees implemented 
- [x] Defense tree designed and implemented
