### ISSUE TITLE
Saving/Loading

### ISSUE THREAD

**Issue by tgrkzus** [UQdeco2800/deco2800-2017-rocketpotatoes#78]
# **Description**
Saving/loading will be implemented by simply serializing the entire game state. It won't be particularly performant but I doubt we will require performance. Multiplayer will be partially supported, a host should be able to load a game and then have clients connect. 

Due the nature of serialization it's like to break anytime anything is changed. So previous saves won't be supported. To support previous saves is generally an incredibly tedious and manual process and I no thanks.

# **Milestone**
-  [ ] Serialization of required state and saving to file.
-  [ ] Loading of serialized data
-  [ ] Interface updates to main menu
-  [ ] Error handling for out of date saves

# **Members**
- Tom Richardson (GH: @tgrkzus Slack: @tomgr)
- More pls?
