### ISSUE TITLE
Enemy Movement - Team 1

### ISSUE THREAD

**Issue by ashfordneil** [UQdeco2800/deco2800-2017-rocketpotatoes#9]
# Description
Adds path finding and movement based animations for the enemies. At this point the enemies are very easy to fool, making the game overly simple. On completion of this ticket, enemies will follow the player more intelligently, and will animate in a way that depends on their movement / direction.

## Path Finding
Enemies should look at the map, find optimal paths to the player / goal, and follow them - avoiding all obstacles in their way. The target of the enemy can be configured depending on game parameters and what we want the enemies to attack.

## Animation
Sprites for the enemies should change based on the direction the enemy is facing, as well as its speed.

# Milestones
## Map Processing
- [x] Set which entities to path around
- [x] Generate nodes in open space around those wall entities
- [x] Generate edges between nodes and check the edges go through open space & do not collide with wall entities.
- [ ] Add a method to update the nodes & edges without having to reprocess every node & edge. (for when trees are added/removed)

## Path finding
! half-implemented path finding, squirrel gets stuck on first node
- [x] Paths can be created and enemies can follow them.
- [x] Paths can be automatically determined based on player and enemy location to avoid obstacles.
- [x] Priorities can be set for the enemies when they are calculating paths.
- [ ] Enemies can respond to updates in paths.
- [ ] Enemies can determine and follow paths with no noticeable drop in performance for gameplay.

## Animation
- [x] 2 Main sprites to be created (moving left and right)
- [ ] *OPTIONAL* : 2 more sprites to be created (moving up and down).
- [x] Enemy sprite changes based on direction it is moving.
- [x] Enemy animation changes based on direction and speed.

# Members of group 1
- Neil Ashford (@artemis)
- Andrew Hine (@andhine)
- Reginald Ho (@reginaldho)
- Goh Zen Hao (@gohzenhao)
- Tazman Schmidt (@TazmanSchmidt)
